ALTER TABLE `item_template_virtual`
	ADD COLUMN `spellid_1` MEDIUMINT(8) NOT NULL DEFAULT '0' AFTER `DisenchantID`,
	ADD COLUMN `spelltrigger_1` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellid_1`,
	ADD COLUMN `spellcharges_1` SMALLINT(6) NOT NULL DEFAULT '0' AFTER `spelltrigger_1`,
	ADD COLUMN `spellppmRate_1` FLOAT NOT NULL DEFAULT '0' AFTER `spellcharges_1`,
	ADD COLUMN `spellcooldown_1` INT(11) NOT NULL DEFAULT '-1' AFTER `spellppmRate_1`,
	ADD COLUMN `spellcategory_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellcooldown_1`,
	ADD COLUMN `spellcategorycooldown_1` INT(11) NOT NULL DEFAULT '-1' AFTER `spellcategory_1`,
	ADD COLUMN `spellid_2` MEDIUMINT(8) NOT NULL DEFAULT '0' AFTER `spellcategorycooldown_1`,
	ADD COLUMN `spelltrigger_2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellid_2`,
	ADD COLUMN `spellcharges_2` SMALLINT(6) NOT NULL DEFAULT '0' AFTER `spelltrigger_2`,
	ADD COLUMN `spellppmRate_2` FLOAT NOT NULL DEFAULT '0' AFTER `spellcharges_2`,
	ADD COLUMN `spellcooldown_2` INT(11) NOT NULL DEFAULT '-1' AFTER `spellppmRate_2`,
	ADD COLUMN `spellcategory_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellcooldown_2`,
	ADD COLUMN `spellcategorycooldown_2` INT(11) NOT NULL DEFAULT '-1' AFTER `spellcategory_2`,
	ADD COLUMN `spellid_3` MEDIUMINT(8) NOT NULL DEFAULT '0' AFTER `spellcategorycooldown_2`,
	ADD COLUMN `spelltrigger_3` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellid_3`,
	ADD COLUMN `spellcharges_3` SMALLINT(6) NOT NULL DEFAULT '0' AFTER `spelltrigger_3`,
	ADD COLUMN `spellppmRate_3` FLOAT NOT NULL DEFAULT '0' AFTER `spellcharges_3`,
	ADD COLUMN `spellcooldown_3` INT(11) NOT NULL DEFAULT '-1' AFTER `spellppmRate_3`,
	ADD COLUMN `spellcategory_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellcooldown_3`,
	ADD COLUMN `spellcategorycooldown_3` INT(11) NOT NULL DEFAULT '-1' AFTER `spellcategory_3`,
	ADD COLUMN `spellid_4` MEDIUMINT(8) NOT NULL DEFAULT '0' AFTER `spellcategorycooldown_3`,
	ADD COLUMN `spelltrigger_4` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellid_4`,
	ADD COLUMN `spellcharges_4` SMALLINT(6) NOT NULL DEFAULT '0' AFTER `spelltrigger_4`,
	ADD COLUMN `spellppmRate_4` FLOAT NOT NULL DEFAULT '0' AFTER `spellcharges_4`,
	ADD COLUMN `spellcooldown_4` INT(11) NOT NULL DEFAULT '-1' AFTER `spellppmRate_4`,
	ADD COLUMN `spellcategory_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellcooldown_4`,
	ADD COLUMN `spellcategorycooldown_4` INT(11) NOT NULL DEFAULT '-1' AFTER `spellcategory_4`,
	ADD COLUMN `spellid_5` MEDIUMINT(8) NOT NULL DEFAULT '0' AFTER `spellcategorycooldown_4`,
	ADD COLUMN `spelltrigger_5` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellid_5`,
	ADD COLUMN `spellcharges_5` SMALLINT(6) NOT NULL DEFAULT '0' AFTER `spelltrigger_5`,
	ADD COLUMN `spellppmRate_5` FLOAT NOT NULL DEFAULT '0' AFTER `spellcharges_5`,
	ADD COLUMN `spellcooldown_5` INT(11) NOT NULL DEFAULT '-1' AFTER `spellppmRate_5`,
	ADD COLUMN `spellcategory_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' AFTER `spellcooldown_5`,
	ADD COLUMN `spellcategorycooldown_5` INT(11) NOT NULL DEFAULT '-1' AFTER `spellcategory_5`;
